platform :ios, '13.0'

# CocoaPods analytics sends network stats. Disable it for build speed
disable_input_output_paths_validation!

def flutter_install_all_ios_pods(directory)
  flutter_provider = File.expand_path(File.join(directory, '..', '..', '..', '..', 'packages', 'flutter_tools', 'bin', 'podhelper.rb'))
  require flutter_provider
  flutter_install_all_ios_pods directory
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
    end
  end
end
